# Generated by Django 4.2.5 on 2023-09-13 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daytripperapi.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='PackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytripperapi.packitem')),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=155)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.URLField()),
                ('destination', models.CharField(max_length=50)),
                ('num_of_days', models.IntegerField()),
                ('num_of_nights', models.IntegerField()),
                ('climate', models.CharField(max_length=150)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('items_to_pack', models.ManyToManyField(through='daytripperapi.PackList', to='daytripperapi.packitem')),
                ('mode_of_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='daytripperapi.transportationtype')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='daytripperapi.planner')),
            ],
        ),
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='daytripperapi.activity')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='daytripperapi.trip')),
            ],
        ),
        migrations.AddField(
            model_name='packlist',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daytripperapi.trip'),
        ),
        migrations.AddField(
            model_name='packitem',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daytripperapi.planner'),
        ),
        migrations.AddField(
            model_name='packitem',
            name='trips',
            field=models.ManyToManyField(through='daytripperapi.PackList', to='daytripperapi.trip'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='daytripperapi.activitytype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='daytripperapi.trip'),
        ),
    ]
